

services:

  backend:
    build:
      context: ./back_End
    container_name: employee-backend
    ports:
      - "9091:9091"
    environment:
      - SERVER_PORT=9091

  frontend:
    build:
      context: ./front
    container_name: employee-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend